// Generated by nuxi
/// <reference types="nuxt-windicss" />
/// <reference types="@nuxtjs/eslint-module" />
/// <reference types="unplugin-icons" />
/// <reference types="@pinia/nuxt" />
/// <reference types="@nuxtjs/svg" />
/// <reference types="@intlify/nuxt3" />
/// <reference types="@vueuse/nuxt" />
/// <reference path="types/nitro.d.ts" />
/// <reference types="nuxt3" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/vue-shim.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="types/components.d.ts" />
/// <reference path="types/auto-imports.d.ts" />
/// <reference path="imports.d.ts" />

export {}
